version: '3'
services:
  immo-admin-react:
    image: node:latest
    ports:
      - '8080:3000'
    volumes:
      - ../immo-client-vue:/var/www
    working_dir: /var/www
    command: >
      /bin/sh -c "npm install && npm install --save-dev @vitejs/plugin-vue @vitejs/plugin-react && npm run dev"

    environment:
      - NODE_ENV=development
    networks:
      - immo.net

networks:
  immo.net:
    driver: bridge
